trigger:
  branches:
    include:
      - main
  paths:
    include:
      - dev/**
      - qa/**
      - PreProd/**
      - Prod/**

variables:
  CLIENT_ID: "5a7c9b2e-09dd-4b78-b863-de343c1b36e0"
  CLIENT_SECRET: "yOa8Q~KJJ92NdwCK_2HPmxTgE4T7mgbqZ4Ol2aNA"
  SUBSCRIPTION_ID: "905e5ecb-b57f-4908-a061-9861012bdc85"
  TENANT_ID: "9cf21cba-3ac1-4621-a2de-d66ad53e67a0"

stages:
  - stage: Dev
    jobs:
      - job: Deploy_to_Dev
        displayName: 'Deploy'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              az login --service-principal -u $(CLIENT_ID) -p $(CLIENT_SECRET) --tenant $(TENANT_ID)
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
              sudo apt-get update && sudo apt-get install terraform -y
              cd dev
              terraform init
              terraform plan -out=tfplan
              terraform apply -auto-approve tfplan
            displayName: 'Deploy'

