trigger:
  branches:
    include:
      - main
  paths:
    include:
      - dev/**
      - qa/**
      - PreProd/**
      - Prod/**

variables:
  CLIENT_ID: "b3e85598-bcdf-4591-996f-6c36910b3ae5"
  CLIENT_SECRET: "abc7eaba-f72e-41ce-a665-3f65c00455c6"
  SUBSCRIPTION_ID: "7d3398b7-7e76-4a20-b1d7-872bb4a43a4b"
  TENANT_ID: "8dbef737-48de-43b6-8aa4-7b9caf795e68"

stages:
  - stage: Dev
    jobs:
      - job: Deploy_to_Dev
        displayName: 'Deploy'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              az login --service-principal -u $(CLIENT_ID) -p $(CLIENT_SECRET) --tenant $(TENANT_ID)
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
              sudo apt-get update && sudo apt-get install terraform -y
              cd dev
              terraform init
              terraform plan -out=tfplan
              terraform apply -auto-approve tfplan
            displayName: 'Deploy'

